on:
  push:
    branches:
      - main

name: Deploy website on push

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: devzonebd.com
          username: github_ftp@perfex.devzonebd.com
          password: ${{ secrets.NEW_PASSWORD }} # required
          port: 22

          source: "./"     # local folder to upload
          target: "/"      # remote folder (root of your subdomain)

          strip_components: 0
          overwrite: true
          command_timeout: 50m
